config/routes.rb
Rails.application.routes.draw do
  root 'homepage#show'
  resources :letters
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  # GET /letters/1
  # GET /letters/1.json
  def show
  end

end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :destroy]

  # GET /letters
  # GET /letters.json
  def index
    @letters = Letter.all
  end

  # GET /letters/1
  # GET /letters/1.json
  def show
  end

  # GET /letters/new
  def new
    @letter = Letter.new
  end

  # GET /letters/1/edit
  def edit
  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(letter_params)

    respond_to do |format|
      if @letter.save
        format.html { redirect_to @letter, notice: 'Letter was successfully created.' }
        format.json { render :show, status: :created, location: @letter }
      else
        format.html { render :new }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /letters/1
  # PATCH/PUT /letters/1.json
  def update
    respond_to do |format|
      if @letter.update(letter_params)
        format.html { redirect_to @letter, notice: 'Letter was successfully updated.' }
        format.json { render :show, status: :ok, location: @letter }
      else
        format.html { render :edit }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    @letter.destroy
    respond_to do |format|
      format.html { redirect_to letters_url, notice: 'Letter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      params.require(:letter).permit(:name, :sound)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/homepage/show.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="container text-center home">

  <div class="row">
    <div class="col-xs-12">
      <h1>Kōrero Mai</h1>
    </div>
    <div class="col-xs-12">
      <h3>Learn Te Reo!</h3>
    </div>
  </div>

  <div class="row play-btn">
    <a href="<%= letters_path %>">
      <button type="button" class="btn btn-default btn-lg" >
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Play!
      </button>
    </a>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KoreroMai2</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home"/></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
        <ul class="nav navbar-nav">
          <li><a href="#">Korero Mai!<span class="sr-only">(current)</span></a></li>

        </ul>
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= letters_path  %>">Alphabet</a></li>
          <li><a href="#">Contact</a></li>
          <li><a href="#">About</a></li>
        </ul>
      <!-- </div><!/.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <%= yield %>
</body>
</html>

app/views/letters/_form.html.erb
<%= form_for(letter) do |f| %>
  <% if letter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(letter.errors.count, "error") %> prohibited this letter from being saved:</h2>

      <ul>
      <% letter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :sound %>
    <%= f.text_field :sound %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/letters/edit.html.erb
<h1>Editing Letter</h1>

<%= render 'form', letter: @letter %>

<%= link_to 'Show', @letter %> |
<%= link_to 'Back', letters_path %>

app/views/letters/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    'letters', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>


<p id="notice"><%= notice %></p>


<div class="container text-center">
  <div class="row">
    <div class="col-xs-12">
    <h1>Te Reo Māori Alphabet</h1>
    </div>
  </div>


  <ul>
    <% @letters.each do |letter| %>
    <li>
      <tr>
        <td><a href="<%= letter_path(letter) %>"><%= letter.name %></a></td>
        <td><%= letter.sound %></td>
      </tr>
    </li>
    <% end %>

  </ul>

</div>


<!-- <%= link_to 'New Letter', new_letter_path %> -->

app/views/letters/new.html.erb
<h1>New Letter</h1>

<%= render 'form', letter: @letter %>

<%= link_to 'Back', letters_path %>

app/views/letters/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container text-center">

  <audio id="letter-sound" src="/a.mp3">
    Your browser does not support the <code>audio</code> element.
  </audio>

  <button id="letter-button" type="button" class="btn btn-default btn-lg" onclick="play('letter-sound')">
    <%= @letter.name %>
  </button>



</div>